"""Add nullable created_at column to purchase

Revision ID: b5431dceac67
Revises: 
Create Date: 2025-03-09 20:42:01.216644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5431dceac67'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('created_at', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True))
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('purchase', 'created_at')
    # ### end Alembic commands ###
